language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer install

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/phpcs.sh
